stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: ubuntu:latest 
  before_script:
    - apt-get update -qy
    - apt-get install -y lazarus
  script:
    - lazbuild --quiet adimtest.lpi
    - cd build
    - if [ -f "adimtest" ]; then
        ./adimtest;
        export EXIT_CODE=$?;
      else
        export EXIT_CODE=255;
      fi
    - exit $EXIT_CODE

  artifacts:
    paths:
      - adim.pas
      - adimpack.pas
      - adimpack.lpk      

